// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPnp515gUX9qNmxhjSWNXnjrXFsAYkE8U',
    appId: '1:332606732961:web:5622c729315e26ccf5cee0',
    messagingSenderId: '332606732961',
    projectId: 'reddit-clone-3e64f',
    authDomain: 'reddit-clone-3e64f.firebaseapp.com',
    storageBucket: 'reddit-clone-3e64f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyVw-kmV9I9ywkodbkfPjfR30YOmFDKN0',
    appId: '1:332606732961:android:72a37955f343e6def5cee0',
    messagingSenderId: '332606732961',
    projectId: 'reddit-clone-3e64f',
    storageBucket: 'reddit-clone-3e64f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAXNEranViy4jktIuXqsV6ngs-J3ZM958',
    appId: '1:332606732961:ios:e504c93538be59d3f5cee0',
    messagingSenderId: '332606732961',
    projectId: 'reddit-clone-3e64f',
    storageBucket: 'reddit-clone-3e64f.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAXNEranViy4jktIuXqsV6ngs-J3ZM958',
    appId: '1:332606732961:ios:32286e7e95ff8370f5cee0',
    messagingSenderId: '332606732961',
    projectId: 'reddit-clone-3e64f',
    storageBucket: 'reddit-clone-3e64f.appspot.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
